### ISSUE TITLE
“隔”字不符合国标写法

### ISSUE THREAD

**Issue by Gliese-876** [lxgw/kose-font#1]
“隔”字不符合国标写法。
该字体：![mmexport1589949540008](https://user-images.githubusercontent.com/63009545/82405576-e7072b00-9a96-11ea-84a8-7fd1c56d92ff.jpg)
百度上的示例：
![b978a8ece01ab48978f0a8a9fb1384370](https://user-images.githubusercontent.com/63009545/82405645-19b12380-9a97-11ea-9671-b079bf72f288.gif)

**Comment by lxgw** [comment]
最近准备把 GB2312 范围内的所有汉字都修改一下。

**Comment by lxgw** [comment]
已更新。
https://github.com/lxgw/kose-font/blob/master/history.md
