### ISSUE TITLE
将 XiaolaiMonoSC 和 Kosefont-JP 标记为等宽字体

### ISSUE THREAD

**Issue by lhy7889678** [lxgw/kose-font#13]
有些老程序（如某些 galgame）在选择字体时，出于技术限制（如某些地方需要文本对齐），只允许使用等宽字体。

字体等宽与否是根据字体信息来判断的，在 FontForge 中可通过 `字体信息 → OS/2 → 特征 → 比例 → 单一间距` 来将字体标记为等宽（英文界面下为 `Font Info → OS/2 → Panose → Proportion → Monospaced`）。FontCreator 我没用过，但应该也有类似的设置。

希望落霞孤鹜大大能够将 XiaolaiMonoSC 和 Kosefont-JP 标记为等宽字体，以方便这些程序识别使用。其他字体项目如涉及等宽字体，也可以考虑修改一下。

（顺便一提，“宋体”(SimSun) 和“新宋体”(NSimSun) 的锅就是这么来的……）

**Comment by lhy7889678** [comment]
更新：事情好像要比我想象的要复杂一些……

小濑字体被标记为等宽字体后，在 Windows 自带的字体预览界面中，所有汉字的宽度都会加倍，且在有些程序中无法正常显示（会被 fallback 到 MS Gothic）。而原版的濑户字体被标记为等宽字体后则不存在这些问题，不知道是什么原因。感觉掉进全角半角的屎山里了……

**Comment by lxgw** [comment]
[已更新 v3.111](https://github.com/lxgw/kose-font/releases/tag/v3.111)。

**Comment by lxgw** [comment]
> 更新：事情好像要比我想象的要复杂一些……
> 
> 小濑字体被标记为等宽字体后，在 Windows 自带的字体预览界面中，所有汉字的宽度都会加倍，且在有些程序中无法正常显示（会被 fallback 到 MS Gothic）。而原版的濑户字体被标记为等宽字体后则不存在这些问题，不知道是什么原因。感觉掉进全角半角的屎山里了……

应该是 `AverageCharWidth` 的原因，用 ttfname3 导出字体元信息的 xml 文件，把 `AverageCharWidth` 值改成 500，再重新合并到字体文件里就可以了。
