### ISSUE TITLE
請問一下小賴字體要不要把部分的舊字形改為新字形？

### ISSUE THREAD

**Issue by UltimateAmitieKaiNiC** [lxgw/kose-font#2]
雖然陸標的骨是新字形，但是「體」的骨字大部分不是新字形。
要不要把部分舊字形改為新字形？

**Comment by NightFurySL2001** [comment]
體字并未在《通用规范汉字表》内，看起来除非作者愿意，否则应该是不会更动繁体字部分。
而且原版字体的很多旧字形都已经被修改成新字形了，再换下去可能会开始脱离风格...
台标的可以看看Max的[内海字体](https://github.com/max32002/naikaifont)。换台标换得差不多脱离风格了...

**Comment by lxgw** [comment]
暫時只改 GB 2312 和《通用規範漢字表》裏的簡體字，繁體字不改。
如果想要臺標的，可以參閱 [內海字體](https://github.com/max32002/naikaifont) ，或者 [cjkFonts 全瀨體](https://www.cjkfonts.io/blog/cjkfonts_allseto) 。

**Comment by UltimateAmitieKaiNiC** [comment]
因為瀨戶字體原作者的韓文不完整，全瀨體的韓文補上了

**Comment by UltimateAmitieKaiNiC** [comment]
既然有了韓文，那麼字體的名稱再加上韓文：샤오라이 글꼴

**Comment by NightFurySL2001** [comment]
@UltimateAmitieKaiNiC 不能因为增加了谚文而就能说支援韩文吧… 至少也要像思源一样支援 [KS X 1001](https://zh.wikipedia.org/wiki/KS_X_1001) 和 [KS X 1002](https://ko.wikipedia.org/wiki/KS_X_1002) 内的汉字字形。
