### ISSUE TITLE
「～（U+FF5E）」符号在竖排时不会自动旋转

### ISSUE THREAD

**Issue by ipid** [lxgw/kose-font#3]
我在做漫画嵌字时使用了小赖字体的 SC 非等宽版本。

在 PS 中打竖排字的时候，「～（U+FF5E）」符号不会自动旋转为竖的波浪线。

按照[小赖字体的文档](https://github.com/lxgw/kose-font/blob/master/OpenType_Features.md)，该字体支持竖排波浪线，是我的使用方式有误还是字体不支持该符号？

**Comment by ipid** [comment]
![image](https://user-images.githubusercontent.com/5251264/88635465-43677600-d0ea-11ea-83c1-0b7e1e8d24a2.png)

如果使用 FontCreator 来手动增加竖排字形替换规则的话，符号就能正确旋转，目前先暂时这么解决了。

**Comment by lxgw** [comment]
收到，下个版本会更新，今天 3.1 版更新完了，才看到这条 Issue。
