### ISSUE TITLE
缺字

### ISSUE THREAD

**Issue by HenryAWE** [lxgw/kose-font#6]
缺少“𩉜”（`⿰革几`）字，即“鞿”的简体字；见于《离骚》：“余虽好修姱以𩉜羁兮”。

**Comment by Hulenkius** [comment]
𩉜似不在通规表中。通规表外不类推，故该字型未收入。人教版教材强行类推不可取（（

**Comment by lxgw** [comment]
由于「鞿（简化）」既不在通规表也不在 GB 18030 范围内，所以目前没有新增这个汉字的计划。不过日后可能会考虑补充 [「入通规经」](http://zhs.glyphwiki.org/wiki/Group:honoka55_%e9%80%9a%e8%a7%84%e5%a4%96%e5%b8%b8%e7%94%a8%e5%ad%97)。
